services:
  - type: web
    name: prometheusweb
    env: node
    buildCommand: |
      apt-get update && apt-get install -y lua5.1 git
      git clone https://github.com/levno-710/Prometheus.git
      npm install
    startCommand: npm start
